ALTER TABLE CompanySetting ADD COLUMN backupTime VARCHAR(191) DEFAULT '02:00';
ALTER TABLE CompanySetting ADD COLUMN backupDay INT DEFAULT 1;
ALTER TABLE CompanySetting ADD COLUMN backupPath VARCHAR(191) NULL;
