export const WORLD_COUNTRIES = [
  { value: "Afganistán", label: "Afganistán" },
  { value: "Alemania", label: "Alemania" },
  { value: "Arabia Saudita", label: "Arabia Saudita" },
  { value: "Argentina", label: "Argentina" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Bélgica", label: "Bélgica" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Brasil", label: "Brasil" },
  { value: "Canadá", label: "Canadá" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "China" },
  { value: "Colombia", label: "Colombia" },
  { value: "Corea del Sur", label: "Corea del Sur" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Dinamarca", label: "Dinamarca" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egipto", label: "Egipto" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Emiratos Árabes Unidos", label: "Emiratos Árabes Unidos" },
  { value: "España", label: "España" },
  { value: "Estados Unidos", label: "Estados Unidos" },
  { value: "Francia", label: "Francia" },
  { value: "Grecia", label: "Grecia" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Honduras", label: "Honduras" },
  { value: "India", label: "India" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Irlanda", label: "Irlanda" },
  { value: "Israel", label: "Israel" },
  { value: "Italia", label: "Italia" },
  { value: "Japón", label: "Japón" },
  { value: "Marruecos", label: "Marruecos" },
  { value: "México", label: "México" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Noruega", label: "Noruega" },
  { value: "Nueva Zelanda", label: "Nueva Zelanda" },
  { value: "Países Bajos", label: "Países Bajos" },
  { value: "Panamá", label: "Panamá" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Perú", label: "Perú" },
  { value: "Polonia", label: "Polonia" },
  { value: "Portugal", label: "Portugal" },
  { value: "Reino Unido", label: "Reino Unido" },
  { value: "República Dominicana", label: "República Dominicana" },
  { value: "Rusia", label: "Rusia" },
  { value: "Singapur", label: "Singapur" },
  { value: "Sudáfrica", label: "Sudáfrica" },
  { value: "Suecia", label: "Suecia" },
  { value: "Suiza", label: "Suiza" },
  { value: "Turquía", label: "Turquía" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" }
].sort((a, b) => a.label.localeCompare(b.label));
